AWSTemplateFormatVersion: '2010-09-09'
Description: 'Minimal CloudFormation template for Node.js backend deployment on Elastic Beanstalk'

Parameters:
  ApplicationName:
    Type: String
    Default: 'contact-us-backend'
    Description: 'Name of the Elastic Beanstalk application'
  
  EnvironmentName:
    Type: String
    Default: 'contact-us-backend-dev'
    Description: 'Name of the Elastic Beanstalk environment'

Resources:
  # Elastic Beanstalk Application
  ElasticBeanstalkApplication:
    Type: AWS::ElasticBeanstalk::Application
    Properties:
      ApplicationName: !Ref ApplicationName
      Description: 'Contact Us Backend Application'

  # Elastic Beanstalk Environment
  ElasticBeanstalkEnvironment:
    Type: AWS::ElasticBeanstalk::Environment
    Properties:
      ApplicationName: !Ref ElasticBeanstalkApplication
      EnvironmentName: !Ref EnvironmentName
      SolutionStackName: '64bit Amazon Linux 2023 v6.1.7 running Node.js 20'
      OptionSettings:
        - Namespace: aws:autoscaling:launchconfiguration
          OptionName: InstanceType
          Value: t3.micro
        - Namespace: aws:elasticbeanstalk:environment
          OptionName: EnvironmentType
          Value: SingleInstance
        - Namespace: aws:elasticbeanstalk:application:environment
          OptionName: NODE_ENV
          Value: 'production'
        - Namespace: aws:elasticbeanstalk:application:environment
          OptionName: PORT
          Value: '8080'

Outputs:
  ApplicationURL:
    Description: 'URL of the Elastic Beanstalk application'
    Value: !Sub 'http://${ElasticBeanstalkEnvironment}.${AWS::Region}.elasticbeanstalk.com'
    Export:
      Name: !Sub '${AWS::StackName}-ApplicationURL'
  
  EnvironmentName:
    Description: 'Name of the Elastic Beanstalk environment'
    Value: !Ref ElasticBeanstalkEnvironment
    Export:
      Name: !Sub '${AWS::StackName}-EnvironmentName'
