const mongoose = require('mongoose');

const aboutContentSchema = new mongoose.Schema({
  // Hero Section Content
  heroSection: {
    mainTitle: {
      type: String,
      default: 'We are'
    },
    rotatingTexts: {
      type: [String],
      validate: {
        validator: function (v) {
          return v.length >= 1 && v.length <= 10;
        },
        message: 'Hero section must have between 1 and 10 rotating texts'
      },
      default: ['Full-Service', 'AI Infused', 'Mar-Tech', 'Creative',]
    },
    backgroundVideo: {
      type: String,
      default: '/hero.mp4'
    },
    heroImages: {
      type: [String],
      validate: {
        validator: function (v) {
          return v.length >= 1 && v.length <= 10;
        },
        message: 'Hero section must have between 1 and 10 hero images'
      },
      default: ['/fullservice.jpeg', '/ai.jpeg', '/tech.jpeg', '/creative.jpeg']
    }
  },

  // Parallax Section Content  
  parallaxSection: {
    title: {
      type: String,
      default: 'Your Voice in the Future of Marketing.'
    },
    backgroundImage: {
      type: String,
      default: '/voice.jpg'
    }
  },

  // Services Section Content
  servicesSection: {
    title: {
      type: String,
      default: 'Our Services'
    },
    backgroundImage: {
      type: String,
      default: '/serviceVector.png'
    },
    cards: {
      type: [{
        id: { type: String, required: true },
        title: { type: String, required: true },
        description: { type: String, required: true },
        image: { type: String, required: true },
        tags: { type: [String], required: true },
        imagePosition: {
          type: String,
          enum: ['left', 'right'],
          default: 'left'
        },
        order: { type: Number, required: true },
        isActive: { type: Boolean, default: true }
      }],
      default: [
        {
          id: 'strategy',
          title: 'Strategy',
          description: 'We translate your aspirations into a precise and actionable blueprint for achieving your goals.',
          image: '/strategy.jpeg',
          tags: ['Brand Strategy', 'Brand Voice', 'GTM Strategy', 'Campaign Strategy', 'PR Strategy', 'Social Media Strategy'],
          imagePosition: 'left',
          order: 1,
          isActive: true
        },
        {
          id: 'branding-design',
          title: 'Branding & Design',
          description: 'We transform your vision into a tangible and impactful brand experience.',
          image: '/brand.jpg',
          tags: ['Brand Identity Design', 'Office Branding', 'Event Branding', 'Print & Digital Creatives', 'Website Design', 'UI/UX Design'],
          imagePosition: 'right',
          order: 2,
          isActive: true
        },
        {
          id: 'content-production',
          title: 'Content & Production',
          description: 'We bring your story to life, crafting impactful content experiences that resonate.',
          image: '/content.jpeg',
          tags: ['Influencer Marketing', 'Conceptualization of Content', 'High Quality Video Shoot & Production', 'Reel Production', 'Motion Graphics', 'Creative Copywriting', 'Blogs / Articles'],
          imagePosition: 'left',
          order: 3,
          isActive: true
        },
        {
          id: 'digital-marketing',
          title: 'Digital Marketing',
          description: 'We convert digital footprints into tangible results, connecting you with your audience and driving results.',
          image: '/digital.jpeg',
          tags: ['Growth Marketing (Push & Pull Mediums)', 'Social Media Management Packages', 'SEO Optimization & Ranking'],
          imagePosition: 'right',
          order: 4,
          isActive: true
        },
        {
          id: 'agent-vua',
          title: 'Agent Vua',
          description: 'AI Powered Calling Agent for all your Pre-Sales / Post-Sales & Customer Support Requirements',
          image: '/vua.jpeg',
          tags: ['AI Powered, Human like conversations', 'Real time objection handling', 'CRM Integrated', 'Available 24*7'],
          imagePosition: 'left',
          order: 5,
          isActive: true
        },
        {
          id: 'agent-vision',
          title: 'Agent Vision',
          description: 'Fast, Affordable, Production Quality Films – Generated by AI',
          image: '/vision.png',
          tags: ['Project Walkthroughs', 'Launch Videos', 'Reel / Content Generation', 'Production & Films'],
          imagePosition: 'right',
          order: 6,
          isActive: true
        },
        {
          id: 'agent-xr',
          title: 'Agent XR',
          description: 'Don\'t leave it to their Imagination, Immerse them in the Experience',
          image: '/xr.jpeg',
          tags: ['Virtual Reality', 'Digital Twins', 'Mixed Reality', 'Realistic Renderings'],
          imagePosition: 'left',
          order: 7,
          isActive: true
        }
      ]
    }
  },

  // About Text Lines
  aboutTitle: {
    type: String,
    default: 'About Us'
  },
  aboutTextLines: {
    type: [String],
    default: [
      'Lorem Ipsum Dolor Sit Amet, Consectetuer Adipiscing Elit, Sed',
      'Diam Nonummy Nibh Euismod Tincidunt Ut Laoreet Dolore Magna',
      'Aliquam Erat Volutpat. Ut Wisi Enim Ad Minim Veniam, Quis Nostrud',
      'Exerci Tation Ullamcorper Suscipit Lobortis Nisl Ut Aliquip Ex Ea',
      'Commodo Consequat.'
    ]
  },

  // Foundation Section Content
  foundationSection: {
    title: {
      type: String,
      default: 'Our Foundation'
    },
    foundations: {
      type: [{
        title: { type: String, required: true },
        description: { type: String, required: true },
        order: { type: Number, required: true }
      }],
      default: [
        {
          title: 'Creativity',
          description: 'Creativity that inspires',
          order: 1
        },
        {
          title: 'Innovation',
          description: 'Technology that keeps You ahead',
          order: 2
        },
        {
          title: 'Strategic Thinking',
          description: 'Strategy that always makes you win',
          order: 3
        },
        {
          title: 'Customer Centricity',
          description: 'Everything is about "You"',
          order: 4
        }
      ]
    },
    backgroundColor: {
      type: String,
      default: '#6310FF'
    }
  },

  // Video Section Content
  videoSection: {
    videoSrc: {
      type: String,
      default: '/vua-intro.mp4'
    },
    backgroundColor: {
      type: String,
      default: '#EEF0FF'
    }
  },

  // Metadata
  isActive: {
    type: Boolean,
    default: true
  },
  version: {
    type: String,
    default: '1.0'
  },
  lastUpdatedBy: {
    type: String,
    trim: true
  },
  createdAt: {
    type: Date,
    default: Date.now
  },
  updatedAt: {
    type: Date,
    default: Date.now
  }
});

// Pre-save hook to ensure only one active content version
aboutContentSchema.pre('save', async function (next) {
  if (this.isActive) {
    // Deactivate all other active versions
    await this.constructor.updateMany(
      { _id: { $ne: this._id } },
      { $set: { isActive: false } }
    );
  }

  // Validate rotating texts length (1-10)
  if (this.heroSection && this.heroSection.rotatingTexts) {
    if (this.heroSection.rotatingTexts.length < 1) {
      this.heroSection.rotatingTexts = ['Full-Service'];
    } else if (this.heroSection.rotatingTexts.length > 10) {
      this.heroSection.rotatingTexts = this.heroSection.rotatingTexts.slice(0, 10);
    }
  }

  // Validate hero images length (1-10)
  if (this.heroSection && this.heroSection.heroImages) {
    if (this.heroSection.heroImages.length < 1) {
      this.heroSection.heroImages = ['/fullservice.jpeg'];
    } else if (this.heroSection.heroImages.length > 10) {
      this.heroSection.heroImages = this.heroSection.heroImages.slice(0, 10);
    }
  }

  // Ensure foundation items have proper order
  if (this.foundationSection && this.foundationSection.foundations) {
    // Ensure proper order based on index if not set or duplicate
    this.foundationSection.foundations.forEach((foundation, index) => {
      foundation.order = index + 1;
    });
  }

  this.updatedAt = new Date();
  next();
});

// Method to get cards sorted by order
aboutContentSchema.methods.getSortedCards = function () {
  return this.servicesSection.cards
    .filter(card => card.isActive)
    .sort((a, b) => a.order - b.order);
};

// Method to get foundations sorted by order
aboutContentSchema.methods.getSortedFoundations = function () {
  return this.foundationSection.foundations
    .sort((a, b) => a.order - b.order);
};

// Static method to get active content
aboutContentSchema.statics.getActiveContent = async function () {
  const activeContent = await this.findOne({ isActive: true });

  if (!activeContent) {
    // Return default content if none exists
    return new this();
  }

  return activeContent;
};

module.exports = mongoose.model('AboutContent', aboutContentSchema);